// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Keep the module import-safe even when Supabase is disabled.
  console.warn(
    "Supabase environment variables are missing. If the app is supposed to run without Supabase, this is OK.",
    "Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env.local to enable Supabase."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL ?? "https://invalid.supabase.co", SUPABASE_PUBLISHABLE_KEY ?? "invalid", {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Helper function for demo login - handles email confirmation requirements
 */
export async function createAndSignInDemoUser(email: string, password: string, fullName: string, role: "rider" | "driver", vehicleDetails?: any) {
  try {
    // First, try to get the session to see if already logged in
    const { data: { session } } = await supabase.auth.getSession();
    if (session) {
      await supabase.auth.signOut();
    }

    // Try signing up
    const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
      email,
      password,
      options: {
        data: { full_name: fullName },
        emailRedirectTo: window.location.origin,
      }
    });

    if (signUpError) {
      // If user already exists, that's fine
      if (!signUpError.message.includes("User already registered")) {
        throw signUpError;
      }
    }

    // Now try to sign in - if email confirmation is disabled, this will work
    const { data: signInData, error: signInError } = await supabase.auth.signInWithPassword({
      email,
      password,
    });

    if (signInError) {
      throw signInError;
    }

    // If we got here, create the role record
    if (signInData.user) {
      // Create user role
      await supabase.from("user_roles").upsert({
        user_id: signInData.user.id,
        role,
      });

      // If driver, create vehicle
      if (role === "driver" && vehicleDetails) {
        await supabase.from("vehicles").upsert({
          user_id: signInData.user.id,
          ...vehicleDetails,
        });
      }
    }

    return signInData;
  } catch (error) {
    console.error("Demo user creation error:", error);
    throw error;
  }
}